name: go

on:
  push:
     branches: [master]
  pull_request:
      branches: [master]

jobs:
 myci:
   runs-on: ubuntu-latest

   
   steps:
      - name: LS output before
        run: ls
     
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: LS Output
        run: ls

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1

      - name: Build an image from Dockerfile
        run: |
            docker build -t docker.io/sjsjsikem/git-cicd:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/sjsjsikem/git-cicd:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: 'tmy2517@gmail.com'
          password: 'Tmy78044#'

      - name: Extract metadata(tags,labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with: 
            images: 'sjsjsikem/git-cicd1'

      - name: Build and push
        uses: docker/build-push-action@v5
        with: 
            context: .
            push: true
            tags: 'sjsjsikem/git-cicd1'
            labels: 'sjsjsikem/git-cicd1'

      - name: Send custom JSON data to Slack workflow
        uses: slackapi/slack-github-action@v1.24.0
        env:
         SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

        with:
    # For posting a rich message using Block Kit
           payload: |
              {
                "text": "GitHub Action build result: ${{ job.status }}\n",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "GitHub Action build result: ${{ job.status }}\n"
                    }
                  }
                ]
              }
          

      - uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{secrets.SLACK_TOKEN}}
          channel_id: 'test-submission'
          content: 'file content'
          file_type: 'table'
          file_name: 'text.txt'
          title: 'title of file'
          initial_comment: 'post by slack-upload-file'
          # thread_ts: 'option'
              
            
            
            

