name: go

on:
  push:
     branches: [master]
  pull_request:
      branches: [master]

jobs:
 myci:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.12.0
            
            
