name: go

on:
  push:
     branches: [master]
  pull_request:
      branches: [master]

jobs:
 myci:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          reposity: 'github.git-cicd'
          ref: 'master'
          token: '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'
          ssh-key: 'git@github.com:sjsjsikem/git-cicd.git'
          ssh-known-hosts: 'ssh-keyscan github.com'
          
          

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 

      - name: Login to Docker HUb
        uses: docker/login-action@v3
        with:
            username: tmy2517@gmail.com
            password: Tmy78044#

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: user/app:latest
       
