name: Build and Push

on:
  push:
     branches: [master]
  pull_request:
      branches: [master]

jobs:
 myci:
   runs-on: ubuntu-latest

   permissions:
      contents: read
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token


   
   steps:
      - name: LS output before
        run: ls
     
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: LS Output
        run: ls      

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: ${{secrets.INFORM}}
          SLACK_TITLE: Build and Sign
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Upload file
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          content: 'file content'
          file_name: 'output.txt'
          title: 'Report'
          initial_comment: 'post by slack-upload-file'
